#!/bin/sh

eval "$(luarocks path)"
export PATH="$(pwd)/src/bin/:$PATH"
export LUA_PATH="$(pwd)/src/?.lua;$LUA_PATH"
export CFLAGS='-O3 -std=c99 -Wall -Werror -Wundef -Wpedantic -Wno-unused'

run_bench() {
    local repetitions="$1"
    shift
    local benchmark_name="$1"
    shift
    local benchmark_args="$@"

    local benchmark_dir="benchmarks/$benchmark_name"
    #echo --Pallene--
    local precision=9
    local acc=0
    local output
    for i in $(seq $repetitions); do
        output="$(benchmarks/run --mode perf \
            "$benchmark_dir/pallene.pln" $benchmark_args)"
        local t="$( echo "$output" | awk '/seconds time elapsed/ {print $1};')"
        acc="$(echo "scale = 7; $acc + $t" | bc)"
    done
    local average="$(echo "scale = 7; $acc/$repetitions" | bc)"
    echo "$benchmark_name" "$average"
    echo "$output" | sed -En '/renormalize|checkgc/p'
}

# remove shared libraries to force recompilation each time
rm benchmarks/*/*.so 2> /dev/null

repetitions=1
cat bench-args | while read args; do run_bench "$repetitions" $args; done
